#!/bin/bash
#
#for nimi in $(cat kasutajad);
#	do
#	sh lisa_kasutaja $nimi
#	done


for nimi in $(cat kasutajad_paroolid | cut -d ":" -f1);
#parool=(cat kasutajad_paroolid)

do
	sh lisa_kasutaja $nimi

done

for parool in $(cat kasutajad_paroolid);

do
	echo $parool | chpasswd
done
