#!/bin/bash
if dpkg-query -W -f='${Status}' nginx mysql-community-server php7.0 php7.0-fpm php7.0-mysql
then
        echo "LAMP stack on paigaldatud"
else
        echo "Andmebaasi kasutaja: "
        read Andmebaas
        echo "Andmebaasi parool: "
        read Parool
        echo "Andmebaasi nimi: "
        read Nimi

#Pakkettide installeerimine ja uuendamine.
                echo "Pakettide uuendamine"
        apt-get update

                echo "Nginx installeerimine."
                sleep 2
        apt-get install nginx -y

                echo "Mysql installeerimine."
                sleep 2
        apt-get install mysql-community-client mysql-community-server -y

                echo "Php7.0 installeerimine"
                sleep 2
        apt-get install php7.0 php7.0-fpm php7.0-mysql -y

                echo "phpmyadmin paigaldamine"
                sleep 2
        apt-get -y install phpmyadmin
        ln -s /usr/share/phpmyadmin/ /var/www/html/phpmyadmin

                echo "Wordpressi paigaldamine"
                sleep 2

wget https://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz


mysql -e "echo "CREATE USER '$Nimi'@'localhost' IDENTIFIED BY '$Parool';"
mysql -e "CREATE DATABASE $Nimi"
mysql -e "GRANT ALL PRIVILEGES ON $Nimi.* TO '$Nimi'@'localhost' IDENTIFIED BY '$Parool';"
mysql -e "FLUSH PRIVILEGES;"
cd wordpress
cp -rf . /var/www/html/wordpress
cd /var/www/html/wordpress
cp wp-config-sample.php wp-config.php
        perl -pi -e "s/database_name_here/$Nimi/g" wp-config.php
        perl -pi -e "s/username_here/$Nimi/g" wp-config.php
        perl -pi -e "s/password_here/$Parool/g" wp-config.php
        perl -i -pe'
        BEGIN {
                @chars = ("a" .. "z", "A" .. "Z", 0 .. 9);
                push @chars, split //, "!@#$%^&*()-_ []{}<>~\`+=,.;:/?|";
                sub salt { join "", map $chars[ rand @chars ], 1 .. 64 }
                }
                s/put your unique phrase here/salt()/ge
        ' wp-config.php
        mkdir wp-content/uploads
        chmod 775 wp-content/uploads
        apt-get -y install phpmyadmin
        ln -s /usr/share/phpmyadmin/ /var/www/html/phpmyadmin
        echo "Kõik on edukale paigaldatud!"
fi

